=== archlinux/archwiki/docs/abstract-schema-table.json
{
	"$schema": "https://json-schema.org/schema#",
	"description": "Abstract description of a mediawiki database table",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string",
			"description": "Name of the table"
		},
		"comment": {
			"type": "string",
			"description": "Comment describing the table"
		},
		"columns": {
			"type": "array",
			"additionalItems": false,
			"description": "Columns",
			"minItems": 1,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "Name of the column"
					},
					"comment": {
						"type": "string",
						"description": "Comment describing the column"
					},
					"type": {
						"type": "string",
						"description": "Data type of the column",
						"enum": [
							"bigint",
							"binary",
							"blob",
							"boolean",
							"datetimetz",
							"decimal",
							"float",
							"integer",
							"mwenum",
							"mwtimestamp",
							"mwtinyint",
							"smallint",
							"string",
							"text"
						]
					},
					"options": {
						"type": "object",
						"description": "Additional options",
						"additionalProperties": false,
						"properties": {
							"autoincrement": {
								"type": "boolean",
								"description": "Indicates if the field should use an autoincremented value if no value was provided",
								"default": false
							},
							"default": {
								"type": [
									"number",
									"string",
									"null"
								],
								"description": "The default value of the column if no value was specified",
								"default": null
							},
							"fixed": {
								"type": "boolean",
								"description": "Indicates if the column should have a fixed length",
								"default": false
							},
							"length": {
								"type": "number",
								"description": "Length of the field.",
								"default": null,
								"minimum": 0
							},
							"notnull": {
								"type": "boolean",
								"description": "Indicates whether the column is nullable or not",
								"default": true
							},
							"unsigned": {
								"type": "boolean",
								"description": "If the column should be an unsigned integer",
								"default": false
							},
							"scale": {
								"type": "number",
								"description": "Exact number of decimal digits to be stored in a decimal type column",
								"default": 0
							},
							"precision": {
								"type": "number",
								"description": "Precision of a decimal type column that determines the overall maximum number of digits to be stored (including scale)",
								"default": 10
							},
							"PlatformOptions": {
								"type": "object",
								"additionalProperties": false,
								"properties": {
									"version": {
										"type": "boolean"
									}
								}
							},
							"CustomSchemaOptions": {
								"type": "object",
								"description": "Custom schema options",
								"additionalProperties": false,
								"properties": {
									"allowInfinite": {
										"type": "boolean"
									},
									"doublePrecision": {
										"type": "boolean"
									},
									"enum_values": {
										"type": "array",
										"description": "Values to use with type 'mwenum'",
										"additionalItems": false,
										"items": {
											"type": "string"
										},
										"uniqueItems": true
									}
								}
							}
						}
					}
				},
				"required": [
					"name",
					"type",
					"options"
				]
			}
		},
		"indexes": {
			"type": "array",
			"additionalItems": false,
			"description": "Indexes",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": {
						"type": "string",
						"description": "Index name"
					},
					"comment": {
						"type": "string",
						"description": "Comment describing the index"
					},
					"columns": {
						"type": "array",
						"additionalItems": false,
						"description": "Columns used by the index",
						"items": {
							"type": "string"
						},
						"uniqueItems": true
					},
					"unique": {
						"type": "boolean",
						"description": "If the index is unique",
						"default": false
					},
					"flags": {
						"type": "array",
						"items": {
							"type": "string",
							"enum": [
								"fulltext",
								"spatial"
							]
						},
						"uniqueItems": true
					},
					"options": {
						"type": "object",
						"properties": {
							"lengths": {
								"type": "array",
								"items": {
									"type": [
										"number",
										"null"
									]
								},
								"minItems": 1
							}
						}
					}
				},
				"required": [
					"name",
					"columns",
					"unique"
				]
			}
		},
		"pk": {
			"type": "array",
			"additionalItems": false,
			"description": "Array of column names used in the primary key",
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		},
		"table_options": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"required": [
		"name",
		"columns",
		"indexes"
	]
}

=== archlinux/archwiki/extensions/CheckUser/schema/cuci_wiki_map.json
[
	{
		"name": "cuci_wiki_map",
		"comment": "A central table used to map an integer ID to wiki DB name. Used to make storage of the wiki IDs more efficient.",
		"columns": [
			{
				"name": "ciwm_id",
				"comment": "Unique ID to identify each wiki ID. This is the primary key, but can be a smallint as it will never exceed the number of wikis in an install (so ~65,000 is enough).",
				"type": "smallint",
				"options": { "unsigned": true, "notnull": true, "autoincrement": true }
			},
			{
				"name": "ciwm_wiki",
				"comment": "The wiki DB name associated with this row.",
				"type": "binary",
				"options": { "notnull": true, "length": 255 }
			}
		],
		"indexes": [
			{
				"name": "ciwm_wiki",
				"columns": [ "ciwm_wiki" ],
				"unique": true,
				"comment": "Used to find the integer ID for a given wiki DB name."
			}
		],
		"pk": [ "ciwm_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/cu_useragent_clienthints_map.json
[
	{
		"name": "cu_useragent_clienthints_map",
		"columns": [
			{
				"name": "uachm_uach_id",
				"comment": "Foreign key to cu_useragent_clienthints uach_id.",
				"type": "integer",
				"options": { "notnull": true, "unsigned": true }
			},
			{
				"name": "uachm_reference_id",
				"comment": "Foreign key to one of cu_changes, cu_log_event, or cu_private_event. Consult uachm_reference_type to determine which table this row relates to.",
				"type": "integer",
				"options": { "unsigned": true, "notnull": true }
			},
			{
				"name": "uachm_reference_type",
				"comment": "Integer mapping identifier specifying which table the data in this row relates to. See UserAgentClientHintsManager for the mapping.",
				"type": "mwtinyint",
				"options": { "notnull": true, "length": 1, "default": 0 }
			}
		],
		"indexes": [
			{ "name": "uachm_reference_id", "columns": [ "uachm_reference_id" ], "unique": false }
		],
		"pk": [ "uachm_uach_id", "uachm_reference_type", "uachm_reference_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/cuci_temp_edit.json
[
	{
		"name": "cuci_temp_edit",
		"comment": "A central index table that allows looking up which wikis have temporary account edits in their CheckUser result tables for a given IP or IP range.",
		"columns": [
			{
				"name": "cite_ip_hex",
				"comment": "The IP address associated with this row in hexadecimal form",
				"type": "binary",
				"options": { "notnull": true, "length": 255 }
			},
			{
				"name": "cite_ciwm_id",
				"comment": "ID for a row in the cuci_temp_edit table. That row holds the wiki ID associated with this row.",
				"type": "smallint",
				"options": { "unsigned": true, "notnull": true }
			},
			{
				"name": "cite_timestamp",
				"comment": "The most recent timestamp associated with temporary account edits made on the given wiki and IP address.",
				"type": "mwtimestamp",
				"options": { "notnull": true }
			}
		],
		"indexes": [
			{
				"name": "cite_timestamp",
				"columns": [ "cite_timestamp" ],
				"unique": false,
				"comment": "Used to find rows that should be deleted as the rows they reference will have been purged."
			},
			{
				"name": "cite_ip_hex_timestamp",
				"columns": [ "cite_ip_hex", "cite_timestamp" ],
				"unique": false,
				"comment": "Used to find which wikis were mostly recently edited by temporary accounts for a given IP or IP range."
			}
		],
		"pk": [ "cite_ip_hex", "cite_ciwm_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/tables-virtual-checkuser.json
[
	{
		"name": "cusi_case",
		"comment": "A table used to store suggested investigations to be shown to a checkuser. Used by the the Suggested investigations feature of the CheckUser extension.",
		"columns": [
			{
				"name": "sic_id",
				"comment": "Primary key",
				"type": "integer",
				"options": { "unsigned": true, "notnull": true, "autoincrement": true }
			},
			{
				"name": "sic_status",
				"comment": "Integer acting as an enum, which represents the status of this case. Open is 0, Closed as resolved is 1, Closed as invalid is 2",
				"type": "mwtinyint",
				"options": { "unsigned": true, "notnull": true, "default": 0 }
			},
			{
				"name": "sic_status_reason",
				"comment": "The reason given for changing sic_status to either closed as resolved (1) or closed as invalid (2).",
				"type": "binary",
				"options": { "notnull": true, "length": 255, "default": "" }
			},
			{
				"name": "sic_created_timestamp",
				"comment": "The timestamp representing when the case was created by the system.",
				"type": "mwtimestamp",
				"options": { "notnull": true }
			}
		],
		"indexes": [
			{
				"name": "sic_status_created_timestamp_id",
				"columns": [ "sic_status", "sic_created_timestamp", "sic_id" ],
				"unique": true,
				"comment": "Used for several things. Allows sorting and paging the Codex table by the 'Status' column (the created timestamp and ID are used to ensure unique paging). Also allows the system to find the newest open case given a pre-determined list of sic_id values, so the system can add new users to an existing case."
			},
			{
				"name": "sic_created_timestamp_id",
				"columns": [ "sic_created_timestamp", "sic_id" ],
				"unique": true,
				"comment": "Used to sort and page cases by their creation timestamp (the ID makes paging consistent in case two cases have the same creation timestamp) for the Codex table on the Special page for Suggested investigations."
			}
		],
		"pk": [ "sic_id" ]
	},
	{
		"name": "cusi_user",
		"comment": "A table which represents the accounts in each suggested investigation (a suggested investigation is a row in the cusi_case table). A user can be associated with more than one cusi_case row. Used by the the Suggested investigations feature of the CheckUser extension.",
		"columns": [
			{
				"name": "siu_user_id",
				"comment": "Part of composite primary key. The user ID of the suspicious account this row represents.",
				"type": "integer",
				"options": { "unsigned": true, "notnull": true }
			},
			{
				"name": "siu_sic_id",
				"comment": "Part of composite primary key. The cusi_case row (suggested investigation) that this user is associated with.",
				"type": "integer",
				"options": { "unsigned": true, "notnull": true }
			}
		],
		"indexes": [
			{
				"name": "siu_user_id",
				"columns": [ "siu_user_id" ],
				"unique": false,
				"comment": "Used to find which cusi_case rows that a given user ID is associated with"
			}
		],
		"pk": [ "siu_sic_id", "siu_user_id" ]
	},
	{
		"name": "cusi_signal",
		"comment": "A table that represents a distinct signal-value pair. A signal is used to determine that an account may need investigation and the value is used to group users with the same value. Used by the the Suggested investigations feature of the CheckUser extension.",
		"columns": [
			{
				"name": "sis_sic_id",
				"comment": "Foreign key to the cusi_case row. Used in the composite primary key.",
				"type": "integer",
				"options": { "unsigned": true, "notnull": true }
			},
			{
				"name": "sis_name",
				"comment": "The name of the signal. Used in the composite primary key.",
				"type": "binary",
				"options": { "notnull": true, "length": 255 }
			},
			{
				"name": "sis_value",
				"comment": "The value associated with the signal. Used in the composite primary key.",
				"type": "binary",
				"options": { "notnull": true, "length": 255 }
			}
		],
		"indexes": [
			{
				"name": "sis_sic_id",
				"columns": [ "sis_sic_id" ],
				"unique": false,
				"comment": "Used to find cusi_signal rows for a given cusi_case row, when displaying cusi_case rows in the UI."
			}
		],
		"pk": [ "sis_name", "sis_value", "sis_sic_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/cu_useragent.json
[
	{
		"name": "cu_useragent",
		"comment": "The user agent string header provided by the browser for requests is stored here for de-duplication. There MAY be rows with the same user agent string.",
		"columns": [
			{
				"name": "cuua_id",
				"comment": "Unique ID to identify each user agent",
				"type": "bigint",
				"options": { "unsigned": true, "notnull": true, "autoincrement": true }
			},
			{
				"name": "cuua_text",
				"comment": "The user agent string",
				"type": "binary",
				"options": { "notnull": true, "length": 255 }
			}
		],
		"indexes": [
			{
				"name": "cuua_text",
				"columns": [ "cuua_text" ],
				"unique": false,
				"comment": "Used to find rows with a given user agent string when attempting to insert a new row to one of cu_changes, cu_log_event, cu_private_event, or cu_private_event_no_actor."
			}
		],
		"pk": [ "cuua_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/cu_useragent_clienthints.json
[
	{
		"name": "cu_useragent_clienthints",
		"columns": [
			{
				"name": "uach_id",
				"comment": "Primary key",
				"type": "integer",
				"options": { "autoincrement": true, "notnull": true, "unsigned": true }
			},
			{
				"name": "uach_name",
				"comment": "Name of the user-agent client hint. See https://wicg.github.io/ua-client-hints/#http-ua-hints for a list.",
				"type": "string",
				"options": { "notnull": true, "length": 32 }
			},
			{
				"name": "uach_value",
				"comment": "Value of the user-agent client hint, see https://wicg.github.io/ua-client-hints/#http-ua-hints for a list of client hint names.",
				"type": "string",
				"options": { "notnull": true, "length": 255 }
			}
		],
		"indexes": [
			{
				"name": "uach_name_value",
				"columns": [ "uach_name", "uach_value" ],
				"unique": true
			}
		],
		"pk": [ "uach_id" ]
	}
]

=== archlinux/archwiki/extensions/CheckUser/schema/cuci_user.json
[
	{
		"name": "cuci_user",
		"comment": "A central index table that allows looking up which wikis have actions in their CheckUser result tables for a given central ID. This index may not be complete, as some users (such as bots) may be excluded from the index.",
		"columns": [
			{
				"name": "ciu_central_id",
				"comment": "The central ID associated with this row. The central ID is the ID provided by the CentralIdLookup service, which is the 'user_id' column of the 'user' table without CentralAuth and the 'gu_id' column from the 'globaluser' table with CentralAuth. Both of these columns are integers, so this column is an integer.",
				"type": "integer",
				"options": { "notnull": true, "unsigned": true }
			},
			{
				"name": "ciu_ciwm_id",
				"comment": "ID for a row in the cuci_wiki_map table. That row holds the wiki ID associated with this row.",
				"type": "smallint",
				"options": { "unsigned": true, "notnull": true }
			},
			{
				"name": "ciu_timestamp",
				"comment": "The most recent timestamp for actions associated with this central ID and IP.",
				"type": "mwtimestamp",
				"options": { "notnull": true }
			}
		],
		"indexes": [
			{
				"name": "ciu_timestamp",
				"columns": [ "ciu_timestamp" ],
				"unique": false,
				"comment": "Used to find rows that should be deleted as the rows they reference will have been purged."
			},
			{
				"name": "ciu_central_id_timestamp",
				"columns": [ "ciu_central_id", "ciu_timestamp" ],
				"unique": false,
				"comment": "Used to find which wikis had the most recent actions for a given central ID."
			}
		],
		"pk": [ "ciu_central_id", "ciu_ciwm_id" ]
	}
]
